# ❤️ Heart Disease Prediction Using Machine Learning

## 1. Project Overview

Heart disease is one of the major health problems worldwide. Machine Learning can be used to analyze medical data and predict whether a person is likely to have heart disease based on different health-related attributes.

This project focuses on developing a **Heart Disease Prediction System using Logistic Regression**. The model analyzes patient information such as age, sex, chest pain type, resting blood pressure, cholesterol, maximum heart rate, exercise-induced angina, oldpeak, slope, thalassemia and other medical attributes to predict the presence or absence of heart disease.

## 2. Dataset

The dataset used in this project was obtained from **Kaggle**.

**Dataset Name:** Heart Disease Dataset UCI  
**Dataset File:** `HeartDiseaseTrain-Test.csv`  
**Source:** Kaggle – Heart Disease Dataset UCI by Ketan Gangal

The dataset contains **1,025 records and 14 columns**. It includes both numerical and categorical attributes, with `target` as the output variable.

- `0` → Person does not have heart disease
- `1` → Person has heart disease

## 3. Technologies and Libraries Used

- Python
- Google Colab
- NumPy
- Pandas
- Scikit-learn

## 4. Project Workflow

The project follows these major steps:

1. Import the required Python libraries.
2. Load the Kaggle dataset into a Pandas DataFrame.
3. Explore the dataset and understand its structure.
4. Check for missing values.
5. Perform statistical analysis.
6. Separate the input features and target variable.
7. Convert categorical variables into numerical form using one-hot encoding.
8. Split the dataset into training and testing data using an **80:20 ratio**.
9. Train a **Logistic Regression** model.
10. Evaluate the model using accuracy score.
11. Use the trained model to make a prediction for a new patient's data.

## 5. Data Preprocessing

The dataset contains both numerical and categorical features. The categorical features were converted into numerical features using one-hot encoding with `pd.get_dummies()`.

The target column was separated from the input features before training the model.

The dataset was divided into:

- **80% Training Data:** 820 records
- **20% Testing Data:** 205 records

## 6. Machine Learning Model

### Logistic Regression

Logistic Regression was selected for this project because it is a commonly used classification algorithm for predicting binary outcomes.

The model was trained using the training dataset and then evaluated on both the training and testing datasets.

## 7. Model Performance

The model achieved the following results:

| Dataset | Accuracy |
|---|---:|
| Training Data | **86.95%** |
| Testing Data | **84.88%** |

The testing accuracy of approximately **84.88%** indicates that the Logistic Regression model performs reasonably well on the given dataset.

## 8. Prediction

After training and evaluating the model, a sample patient's medical information was provided to the model. The model generated a prediction indicating whether the person was likely to have heart disease.

## 9. Conclusion

This project demonstrates how Machine Learning can be applied to healthcare-related data for binary classification. Using the Kaggle Heart Disease Dataset UCI and Logistic Regression, the project achieved a testing accuracy of approximately **84.88%**.

The project provides a basic demonstration of the complete Machine Learning workflow, including data collection, preprocessing, feature encoding, model training, evaluation and prediction.

**Note:** This project is developed for educational purposes only. The predictions should not be considered a substitute for professional medical diagnosis.

Importing the Dependencies

In [ ]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score

Data Collection and Processing

In [ ]:
# loading the csv data to a Pandas DataFrame
heart_data = pd.read_csv('/content/HeartDiseaseTrain-Test.csv')

In [ ]:
# print first 5 rows of the dataset
heart_data.head()

,age,sex,chest_pain_type,resting_blood_pressure,cholestoral,fasting_blood_sugar,rest_ecg,Max_heart_rate,exercise_induced_angina,oldpeak,slope,vessels_colored_by_flourosopy,thalassemia,target
0,52,Male,Typical angina,125,212,Lower than 120 mg/ml,ST-T wave abnormality,168,No,1.0,Downsloping,Two,Reversable Defect,0
1,53,Male,Typical angina,140,203,Greater than 120 mg/ml,Normal,155,Yes,3.1,Upsloping,Zero,Reversable Defect,0
2,70,Male,Typical angina,145,174,Lower than 120 mg/ml,ST-T wave abnormality,125,Yes,2.6,Upsloping,Zero,Reversable Defect,0
3,61,Male,Typical angina,148,203,Lower than 120 mg/ml,ST-T wave abnormality,161,No,0.0,Downsloping,One,Reversable Defect,0
4,62,Female,Typical angina,138,294,Greater than 120 mg/ml,ST-T wave abnormality,106,No,1.9,Flat,Three,Fixed Defect,0

In [ ]:
# print last 5 rows of the dataset
heart_data.tail()

,age,sex,chest_pain_type,resting_blood_pressure,cholestoral,fasting_blood_sugar,rest_ecg,Max_heart_rate,exercise_induced_angina,oldpeak,slope,vessels_colored_by_flourosopy,thalassemia,target
1020,59,Male,Atypical angina,140,221,Lower than 120 mg/ml,ST-T wave abnormality,164,Yes,0.0,Downsloping,Zero,Fixed Defect,1
1021,60,Male,Typical angina,125,258,Lower than 120 mg/ml,Normal,141,Yes,2.8,Flat,One,Reversable Defect,0
1022,47,Male,Typical angina,110,275,Lower than 120 mg/ml,Normal,118,Yes,1.0,Flat,One,Fixed Defect,0
1023,50,Female,Typical angina,110,254,Lower than 120 mg/ml,Normal,159,No,0.0,Downsloping,Zero,Fixed Defect,1
1024,54,Male,Typical angina,120,188,Lower than 120 mg/ml,ST-T wave abnormality,113,No,1.4,Flat,One,Reversable Defect,0

In [ ]:
# number of rows and columns in the dataset
heart_data.shape

(1025, 14)

In [ ]:
# getting some info about the data
heart_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1025 entries, 0 to 1024
Data columns (total 14 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   age                            1025 non-null   int64
 1   sex                            1025 non-null   object
 2   chest_pain_type                1025 non-null   object
 3   resting_blood_pressure         1025 non-null   int64
 4   cholestoral                    1025 non-null   int64
 5   fasting_blood_sugar            1025 non-null   object
 6   rest_ecg                       1025 non-null   object
 7   Max_heart_rate                 1025 non-null   int64
 8   exercise_induced_angina        1025 non-null   object
 9   oldpeak                        1025 non-null   float64
 10  slope                          1025 non-null   object
 11  vessels_colored_by_flourosopy  1025 non-null   object
 12  thalassemia                    1025 non-null   object
 13  target                         1025 non-null   int64
dtypes: float64(1), int64(5), object(8)
memory usage: 112.2+ KB

In [ ]:
# checking for missing values
heart_data.isnull().sum()

age                              0
sex                              0
chest_pain_type                  0
resting_blood_pressure           0
cholestoral                      0
fasting_blood_sugar              0
rest_ecg                         0
Max_heart_rate                   0
exercise_induced_angina          0
oldpeak                          0
slope                            0
vessels_colored_by_flourosopy    0
thalassemia                      0
target                           0
dtype: int64

In [ ]:
# statistical measures about the data
heart_data.describe()

,age,resting_blood_pressure,cholestoral,Max_heart_rate,oldpeak,target
count,1025.000000,1025.000000,1025.00000,1025.000000,1025.000000,1025.000000
mean,54.434146,131.611707,246.00000,149.114146,1.071512,0.513171
std,9.072290,17.516718,51.59251,23.005724,1.175053,0.500070
min,29.000000,94.000000,126.00000,71.000000,0.000000,0.000000
25%,48.000000,120.000000,211.00000,132.000000,0.000000,0.000000
50%,56.000000,130.000000,240.00000,152.000000,0.800000,1.000000
75%,61.000000,140.000000,275.00000,166.000000,1.800000,1.000000
max,77.000000,200.000000,564.00000,202.000000,6.200000,1.000000

In [ ]:
# checking the distribution of Target Variable
heart_data['target'].value_counts()

target
1    526
0    499
Name: count, dtype: int64

In [ ]:
heart_data = pd.get_dummies(heart_data, drop_first=True)

In [ ]:
original_columns = heart_data.drop('target', axis=1).columns

1 --> Defective Heart
0 --> Healthy Heart

Splitting the Features and Target

In [ ]:
X = heart_data.drop(columns='target', axis=1)   # whenever dropping column axis is 1 in row it is 0
Y = heart_data['target']

In [ ]:
print(X)

      age  resting_blood_pressure  cholestoral  Max_heart_rate  oldpeak  \
0      52                     125          212             168      1.0
1      53                     140          203             155      3.1
2      70                     145          174             125      2.6
3      61                     148          203             161      0.0
4      62                     138          294             106      1.9
...   ...                     ...          ...             ...      ...
1020   59                     140          221             164      0.0
1021   60                     125          258             141      2.8
1022   47                     110          275             118      1.0
1023   50                     110          254             159      0.0
1024   54                     120          188             113      1.4

      sex_Male  chest_pain_type_Atypical angina  \
0         True                            False
1         True                            False
2         True                            False
3         True                            False
4        False                            False
...        ...                              ...
1020      True                             True
1021      True                            False
1022      True                            False
1023     False                            False
1024      True                            False

      chest_pain_type_Non-anginal pain  chest_pain_type_Typical angina  \
0                                False                            True
1                                False                            True
2                                False                            True
3                                False                            True
4                                False                            True
...                                ...                             ...
1020                             False                           False
1021                             False                            True
1022                             False                            True
1023                             False                            True
1024                             False                            True

      fasting_blood_sugar_Lower than 120 mg/ml  ...  \
0                                         True  ...
1                                        False  ...
2                                         True  ...
3                                         True  ...
4                                        False  ...
...                                        ...  ...
1020                                      True  ...
1021                                      True  ...
1022                                      True  ...
1023                                      True  ...
1024                                      True  ...

      exercise_induced_angina_Yes  slope_Flat  slope_Upsloping  \
0                           False       False            False
1                            True       False             True
2                            True       False             True
3                           False       False            False
4                           False        True            False
...                           ...         ...              ...
1020                         True       False            False
1021                         True        True            False
1022                         True        True            False
1023                        False       False            False
1024                        False        True            False

      vessels_colored_by_flourosopy_One  vessels_colored_by_flourosopy_Three  \
0                                 False                                False
1                                 False                                False
2                                 False                                False
3                                  True                                False
4                                 False                                 True
...                                 ...                                  ...
1020                              False                                False
1021                               True                                False
1022                               True                                False
1023                              False                                False
1024                               True                                False

      vessels_colored_by_flourosopy_Two  vessels_colored_by_flourosopy_Zero  \
0                                  True                               False
1                                 False                                True
2                                 False                                True
3                                 False                               False
4                                 False                               False
...                                 ...                                 ...
1020                              False                                True
1021                              False                               False
1022                              False                               False
1023                              False                                True
1024                              False                               False

      thalassemia_No  thalassemia_Normal  thalassemia_Reversable Defect
0              False               False                           True
1              False               False                           True
2              False               False                           True
3              False               False                           True
4              False               False                          False
...              ...                 ...                            ...
1020           False               False                          False
1021           False               False                           True
1022           False               False                          False
1023           False               False                          False
1024           False               False                           True

[1025 rows x 22 columns]

In [ ]:
print(Y)

0       0
1       0
2       0
3       0
4       0
       ..
1020    1
1021    0
1022    0
1023    1
1024    0
Name: target, Length: 1025, dtype: int64

Splitting the Data into Training data & Test Data

In [ ]:
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.2, stratify=Y, random_state=2)
# test_size=0.2 takes 20 percent data as testing data
# stratify distributes target evenly between testing and training data

In [ ]:
print(X.shape, X_train.shape, X_test.shape)
# 80 percent data in training data and 20 percent in testing

(1025, 22) (820, 22) (205, 22)

Model Training

Logistic Regression

In [ ]:
model = LogisticRegression()

# training the LogisticRegression model with Training data
model.fit(X_train, Y_train)

/usr/local/lib/python3.13/dist-packages/sklearn/linear_model/_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

LogisticRegression()

Model Evaluation

Accuracy Score

In [ ]:
# accuracy on training data
X_train_prediction = model.predict(X_train)
training_data_accuracy = accuracy_score(X_train_prediction, Y_train)

In [ ]:
print('Accuracy on Training data : ', training_data_accuracy)

Accuracy on Training data :  0.8695121951219512

In [ ]:
# accuracy on test data
X_test_prediction = model.predict(X_test)
test_data_accuracy = accuracy_score(X_test_prediction, Y_test)

In [ ]:
print('Accuracy on Testing data : ', test_data_accuracy)

Accuracy on Testing data :  0.848780487804878

Building a Predictive System

In [ ]:
input_data = {
    'age': 41,
    'sex': 'Male',
    'chest_pain': 'Atypical angina',
    'resting_bp': 130,
    'cholesterol': 204,
    'fasting_blood_sugar': 'Lower than 120 mg/dl',
    'resting_ecg': 'Normal',
    'Max_heart_rate': 172,
    'exercise_induced_angina': 'No',
    'oldpeak': 1.4,
    'slope': 'Downsloping',
    'vessels_col': 'Zero',
    'thalassemia': 'Reversible Defect'
}

input_df = pd.DataFrame([input_data])

# Apply exactly the same encoding used for training
input_df = pd.get_dummies(input_df, drop_first=True)

# Make the input have exactly the same 22 columns as X
input_df = input_df.reindex(columns=X.columns, fill_value=False)

# Prediction
prediction = model.predict(input_df)

print(prediction)

[1]

In [ ]:
if (prediction[0] == 0):
    print('The Person does not have a Heart Disease')
else:
    print('The Person has Heart Disease')

The Person has Heart Disease